### ISSUE TITLE
自由拖动的悬浮窗点击事件响应不是很灵敏

### ISSUE THREAD

**Issue by happy-0203** [YoungBill/FloatWindow#1]
你在manifest加上这个属性就灵敏了．
android:hardwareAccelerated="true"
多谢你的反馈，我已经加到项目里了

**Comment by YoungBill** [comment]
你在manifest加上这个属性就灵敏了．
 android:hardwareAccelerated="true"
多谢你的反馈，我已经加到项目里了

**Comment by YoungBill** [comment]
你在manifest加上这个属性就灵敏了．
android:hardwareAccelerated="true"
多谢你的反馈，我已经加到项目里了

**Comment by happy-0203** [comment]
这种方式不是很好,我改了一下你的源码,这样就灵敏了,加上下面几行代码就好了,应该可行

 private final float MINIMUM_DISTANCE = 4.0f;// 手指移动的最小距离
    private int distance;// 根据屏幕密度计算出来的，手指移动的最小距离

 distance = DensityUtil.dip2px(context, MINIMUM_DISTANCE);

   float upX = motionEvent.getRawX();
                        float upY = motionEvent.getRawY();

                        double uX = Math.abs(upX - startDownX);
                        double uY = Math.abs(upY - startDownY);
                        double uL = Math.sqrt(uX * uX + uY * uY);
                        if (uL<distance)
                            return false;
                        else
                            return true;

**Comment by YoungBill** [comment]
可以的。当然android系统提供了一个，判断手指是否移动的最小单位，是一个常量，我忘了叫什么，你也用那个试试。等我看了再给你说。我那种做法，只是提供了一个方案，细节上，你们都可以自我调控的

**Comment by zhaotun** [comment]
怎么点击了都没反应啊，只是能切换activity，没有悬浮窗出现
